// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejbiqmcdxngipbuqvhjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqYmlxbWNkeG5naXBidXF2aGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjY2MzgsImV4cCI6MjA1ODg0MjYzOH0.oFUgA3YCOZqp3yOPWMQ3DdUe52R8D0l2hj49Mvo1hSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);